version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: redbelt_test
    volumes:
      - ./mysql-data:/var/lib/mysql

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    depends_on:
      - db

  php:
    container_name: php
    build: images/php
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db:db
    ports:
      - "9000:9000"
    depends_on:
      - db

  react:
    build: frontend
    container_name: react
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    links:
      - php
